# -*- coding: utf-8 -*-
"""AI_HW0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SS7lVLG-471aE2jZYI-wdoYDbSVtNQ8q
"""

import cv2 as cv

fname = "image.png"
img = cv.imread(fname)

cv.rectangle(img, (608,616), (721,505), (0,0,255), 4)
cv.rectangle(img, (836,557), (916,477), (0,0,255), 4)
cv.rectangle(img, (1073,726), (1180,600), (0,0,255), 4)
cv.rectangle(img, (985,468), (1042,417), (0,0,255), 4)
cv.rectangle(img, (994,383), (1042,346), (0,0,255), 4)
cv.rectangle(img, (1042,314), (1088,282), (0,0,255), 4)
cv.imwrite("hw0_109350008_1.png",img)