# -*- coding: utf-8 -*-
"""AI_HW0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SS7lVLG-471aE2jZYI-wdoYDbSVtNQ8q
"""

import cv2 as cv
import numpy as np

vid = cv.VideoCapture("video.mp4")

img1 = vid.read()[1]
img2 = vid.read()[1]

test = cv.absdiff(img1, img2)
cv.imwrite("hw0_109350008_2.png", np.hstack((img1,test)))

vid.release()
cv.destroyAllWindows()